name       : oath-toolkit
version    : 2.6.2
release    : 1
source     :
    - https://download.savannah.nongnu.org/releases/oath-toolkit/oath-toolkit-2.6.2.tar.gz : b03446fa4b549af5ebe4d35d7aba51163442d255660558cd861ebce536824aa0
license    :
    - LGPL-2.1
    - GPL-3.0
component  : security.library
summary    : One-time password components
description: |
    The OATH Toolkit provide components for building one-time
    password authentication systems. It contains shared libraries,
    command line tools and a PAM module. Supported technologies include
    the event-based HOTP algorithm (RFC4226) and the time-based TOTP
    algorithm (RFC6238). OATH stands for Open AuTHentication, which is
    the organization that specify the algorithms. For managing secret
    key files, the Portable Symmetric Key Container (PSKC) format
    described in RFC6030 is supported.
builddeps  :
    - pkgconfig(xmlsec1)
rundeps    :
    - xmlsec1
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
